CREATE TABLE EMPLOYEE (
	ID			INT	NOT NULL,
	EMPLOYEE_ID	VARCHAR(10) NOT NULL,
	FIRSTNAME	VARCHAR(64) NOT NULL,
	LASTNAME	VARCHAR(64) NOT NULL,
	TITLE		VARCHAR(64) NULL,
	DEPARTMENT	VARCHAR(128) NULL,
	JOIN_DATE	DATE NULL,
	EXPERIENCE	INT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID)
);

CREATE TABLE DEPARTMENTS (
	ID			   INT NOT NULL,
    DEPARTMENT_ID   VARCHAR(10) NOT NULL,
    DEPARTMENT_NAME VARCHAR(128) NOT NULL,
	LEVEL		   INT NOT NULL,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID)
);
